### ISSUE TITLE
Depth Texture not enabled on URP

### ISSUE THREAD

**Issue by javalight** [TinyPlay/URPShadersCollection#2]
If the Depth Texture is not enabled on the URP render pipeline then the water material does **not show Foam on the Game view**, but it will show it in **scene view**. This is true for all current URP water shaders in the asset store. Cheers 🥳

![image](https://user-images.githubusercontent.com/6201595/213838435-59bd3ba6-2ee0-45bf-9667-0c9092d61748.png)

**Comment by TinyPlay** [comment]
Yey! We're add this to documentation.
